# Maintainer : Nguyễn Văn Phi | gunguiuet@gmail.com
sudo: required
language: node_js
node_js:
  - "4.6.2"
  
before_install:
  - "curl -L https://git.io/ejPSng | /bin/sh"
  - npm install -g npm@latest

env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
      
      
